name: "CI: Build Test"

env:
  MINGW_VERSION:  "win64_mingw73"
  MINGW_PATH:     "mingw73_32"

on:
  workflow_dispatch:
    branches: [ master ]
      

jobs:
  build:

    strategy:
      matrix:
        qt_version: [5.12.6, 5.13.2, 5.14.0, 5.15.0, 6.0.0]
        platform: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - qt_version: 6.0.0
            additional_arguments: -D QT_DEFAULT_MAJOR_VERSION=6
          - platform: ubuntu-20.04
            CXXFLAGS: -Wall -Wextra -pedantic -Werror
          - platform: macos-latest
            CXXFLAGS: -Wall -Wextra -pedantic -Werror
          - platform: windows-latest
            CXXFLAGS: /W4 /WX

    runs-on: ${{ matrix.platform }}
    env:
      CXXFLAGS: ${{ matrix.CXXFLAGS }}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.11.1
      with:
        version: ${{ matrix.qt_version }}

    - name: qmake
      run: qmake -makefile
    - name: make
      run: make . ${{ matrix.additional_arguments }}

    - name: Build example - basic (cmake)
      working-directory: examples/basic/
      run: |
        make . ${{ matrix.additional_arguments }}
        make --build .

    - name: Build example - calculator (cmake)
      working-directory: examples/calculator/
      run: |
        make . ${{ matrix.additional_arguments }}
        make --build .

    - name: Build example - sending_arguments (cmake)
      working-directory: examples/sending_arguments/
      run: |
        make . ${{ matrix.additional_arguments }}
        make --build .
