name: MacOS qt6.5 Univarsal cmake C/C++ CI

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.*
        modules: 'qtcharts'
        
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -S ./ -B ./ -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
    - name: make
      run: make
      
    - name: Make CaptureStream executable
      run: chmod -R 755 ./CaptureStream.app
  
    - name: mkdir
      run: mkdir ./build
    - name: cp
      run: mv ./CaptureStream.app ./build/
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream-Univarsal-qt65
        path: ./build

