name: C/C++ CI win

env:
  QT_VERSION:     "5.15.2"


on:
  workflow_dispatch:
   branches: [ master ] 
      
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          - qt_ver: 5.15.2
            qt_arch: win32_msvc2019
            msvc_arch: x86
            qt_arch_install: msvc2019
#        - qt_ver: 5.12.10
#          qt_arch: win32_msvc2017
#          msvc_arch: x86
#          qt_arch_install: msvc2017
#        - qt_ver: 5.11.3
#          qt_arch: win32_mingw53
#          msvc_arch: x86
#          qt_arch_install: mingw53

    env:
      targetName: CaptureStream.exe 
      
    steps:
    
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==2.1.*'
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_mingw81'
          #arch: 'win32_msvc2019'
          # Version of Qt to install
          # version: ${{ matrix.qt_ver }}
          # Target platform for build
          # target: ${{ matrix.qt_target }}
          # arch: ${{ matrix.qt_arch }}
          modules: 'qtcharts qtscript qtwebengine'
          cached: 'false'

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # msvc编译
      - name: msvc-build
        id: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          qmake CaptureStream.pro
          nmake
 #         nmake
      - uses: actions/upload-artifact@v3
        with:
          name: CaptureStream
          path: ./
