name: C/C++ CI Windows

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: Windows-2019

    steps:
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        host: 'windows'
        target: 'desktop'
        version: '5.14.2'
        aqtversion: '==2.1.*'
        archives: 'qtbase qtsvg'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        #arch: 'win64_msvc2019_64'
        #arch: 'win64_mingw81'
        arch: 'win32_mingw81'
        modules: 'Desktop MinGW 8.1.0 32-bit Debug Information Files Qt Charts for MinGW 8.1.0 32-bit Qt Data Visualization for MinGW 8.1.0 32-bit Qt Lottie Animation for MinGW 8.1.0 32-bit Qt Network Authorization for MinGW 8.1.0 32-bit Qt Purchasing for MinGW 8.1.0 32-bit Qt Quick 3D for MinGW 8.1.0 32-bit Qt Quick Timeline for MinGW 8.1.0 32-bit Qt Script for MinGW 8.1.0 32-bit Qt Virtual Keyboard for MinGW 8.1.0 32-bit Qt WebGL Streaming Plugin for MinGW 8.1.0 32-bit'
        tools: 'tools_cmake tools_generic'
        #modules: 'qtcharts qtscript qtwebengine'
        #modules: 'Desktop MinGW 8.1.0 32-bit Debug Information Files Qt Charts for MinGW 8.1.0 32-bit Qt Data Visualization for MinGW 8.1.0 32-bit Qt Lottie Animation for MinGW 8.1.0 32-bit Qt Network Authorization for MinGW 8.1.0 32-bit Qt Purchasing for MinGW 8.1.0 32-bit Qt Quick 3D for MinGW 8.1.0 32-bit Qt Quick Timeline for MinGW 8.1.0 32-bit Qt Script for MinGW 8.1.0 32-bit Qt Virtual Keyboard for MinGW 8.1.0 32-bit Qt WebGL Streaming Plugin for MinGW 8.1.0 32-bit'
        #arch: 'win32_msvc2019'
        #modules: 'Desktop MSVC 2019 Debug Information Files Qt Charts for MSVC 2019 32-bit Qt Data Visualization for MSVC 2019 32-bit Qt Lottie Animation for MSVC 2019 32-bit Qt Network Authorization for MSVC 2019 32-bit Qt Purchasing for MSVC 2019 32-bit Qt Quick 3D for MSVC 2019 32-bit Qt Quick Timeline for MSVC 2019 32-bit Qt Script for MSVC 2019 32-bit Qt Virtual Keyboard for MSVC 2019 32-bit Qt WebEngine for msvc2019 32-bit Qt WebGL Streaming Plugin for MSVC 2019 32-bit'
        #tools: 'tools_cmake tools_generic'
        py7zrversion: '==0.19.*'
        extra: '--external 7z'

        
    - uses: actions/checkout@v3
    - name: qmake
      run: qmake -makefile CaptureStream.pro
    - name: make
      run: make
      
    - name: Make CaptureStream executable
      run: chmod -R 755 ./CaptureStream
  
    - uses: actions/upload-artifact@v3
      with:
        name: CaptureStream
        path: ./CaptureStream
