name: C/C++ CI win

env:
  MINGW_VERSION:  "win64_mingw73"
  MINGW_PATH:     "mingw73_32"

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.9.5'
        host: 'windows'
        target: 'desktop'
        arch:    ${{ env.MINGW_VERSION }}
        install-deps: 'true'
        modules: 'qtcharts qtscript qtwebengine'
        cached: 'false'
        setup-python: 'true'
        tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
        set-env: 'false'
        tools-only: 'false'
        aqtversion: '==1.1.3'
        py7zrversion: '==0.7'
        extra: '--external 7z'
      
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile
    - name: make
      run: make
  
    - uses: actions/upload-artifact@v2
      with:
        name: CaptureStream
        path: ./
