name: C/C++ CI ubuntu

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    #runs-on: ubuntu-22.04
    runs-on: windows-latest

    steps:
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        archtecture: 'x86'

     
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        host: 'windows'
        target: 'desktop'
        version: '5.15.2'
        modules: 'qtcharts qtscript qtwebengine qtdatavis3d qtpurchasing qtnetworkauth qtwebglplugin'
        #dir: '${{ github.workspace }}/example/'
        dir: 'D:\'
        arch: 'win64_msvc2019_64'
        #arch: 'win32_mingw53'
        #arch: 'win32_mingw81'
        #modules: 'qtcharts qtscript qtwebengine qtdatavis3d qtpurchasing qtnetworkauth qtwebglplugin Desktop MinGW 8.1.0 32-bit Debug Information Files Qt Charts for MinGW 8.1.0 32-bit Qt Data Visualization for MinGW 8.1.0 32-bit Qt Lottie Animation for MinGW 8.1.0 32-bit Qt Network Authorization for MinGW 8.1.0 32-bit Qt Purchasing for MinGW 8.1.0 32-bit Qt Quick 3D for MinGW 8.1.0 32-bit Qt Quick Timeline for MinGW 8.1.0 32-bit Qt Script for MinGW 8.1.0 32-bit Qt Virtual Keyboard for MinGW 8.1.0 32-bit Qt WebGL Streaming Plugin for MinGW 8.1.0 32-bit'
        #setup-python: 'fales'
        ##arch: 'gcc_64'
        #modules: 'Desktop gcc 64-bit Debug Information Files Qt Charts for gcc 64-bit Qt Data Visualization for gcc 64-bit Qt Lottie Animation for gcc 64-bit Qt Network Authorization for gcc 64-bit Qt Purchasing for gcc 64-bit Qt Quick 3D for gcc 64-bit Qt Quick Timeline for gcc 64-bit Qt Script for gcc 64-bit Qt Virtual Keyboard for gcc 64-bit Qt Wayland Compositor for gcc 64-bit Qt WebEngine for Desktop gcc 64-bit Qt WebGL Streaming Plugin for gcc 64-bit'

#    - name: Set up MinGW
#      uses: egor-tensin/setup-mingw@v2
#      with:
#       platform: x86

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
        
#    - name: setup GCC
#      uses: egor-tensin/setup-gcc@v1
#      with:
#        version: latest
#        platform: x64
        
    - uses: actions/checkout@v3
    - name: qmake
      run: |
       cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"' win64_msvc2019_64"
       qmake.exe -makefile CaptureStream.pro
    - name: make
      run: make
      
    - name: Make CaptureStream executable
      run: chmod -R 755 ./CaptureStream
  
    - uses: actions/upload-artifact@v3
      with:
        name: CaptureStream
        path: ./
