name: C/C++ CI win

env:
  QT_VERSION:     "5.12.7"
  MINGW_VERSION:  "win32_mingw73"
  MINGW_PATH:     "mingw73_32"

on:
  workflow_dispatch:
   branches: [ master ] 
      
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
        - qt_ver: 5.9.9
          qt_arch: win32_msvc2015
          msvc_arch: x86
          qt_arch_install: msvc2015
        - qt_ver: 5.12.10
          qt_arch: win32_msvc2017
          msvc_arch: x86
          qt_arch_install: msvc2017
        - qt_ver: 5.15.2
          qt_arch: win32_msvc2019
          msvc_arch: x86


    steps:
    
      - name: Install Qt
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          # target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          cached: 'false'
     
      - uses: actions/checkout@v2.3.4

      - name: qmake
        run: qmake -makefile
      - name: make
        run: make
  
      - uses: actions/upload-artifact@v2
        with:
          name: CaptureStream
          path: ./
