name: MacOS Intel C/C++ CI

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.*
        modules: 'qtcharts'
        
    - uses: actions/checkout@v3
    - name: qmake
      run: qmake -makefile CaptureStream.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64"
    - name: make
      run: make
      
    - name: Make CaptureStream executable
      run: chmod -R 755 ./CaptureStream.app
  
    - uses: actions/upload-artifact@v3
      with:
        name: CaptureStream-Intel
        path: ./

