name: C/C++ CI win

env:
  MINGW_VERSION:  "win32_mingw73"
  MINGW_PATH:     "mingw73_32"

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch:    ${{ env.MINGW_VERSION }}
        extra:   --external 7z
        modules: 'qtcharts qtscript qtwebengine'
        
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile
    - name: make
      run: make
  
    - uses: actions/upload-artifact@v2
      with:
        name: CaptureStream
        path: ./
