name: C/C++ CI ubuntu

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'desktop'
        modules: 'qtcharts qtscript qtwebengine'
        set-env: 'false'
        
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile
    - name: make
      run: make
  
    - uses: actions/upload-artifact@v2
      with:
        name: CaptureStream
        path: ./
