name: C/C++ CI win

env:
  QT_VERSION:     "5.12.7"


on:
  workflow_dispatch:
   branches: [ master ] 
      
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
#        - qt_ver: 5.9.9
#          qt_arch: win32_msvc2015
#          msvc_arch: x86
#          qt_arch_install: msvc2015
#        - qt_ver: 5.12.10
#          qt_arch: win32_msvc2017
#          msvc_arch: x86
#          qt_arch_install: msvc2017
        - qt_ver: 5.11.3
          qt_arch: win32_mingw53
          msvc_arch: x86
          qt_arch_install: mingw53

    env:
      targetName: CaptureStream.exe 
      
    steps:
    
      - name: Install Qt
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          # Version of Qt to install
         # version: ${{ matrix.qt_ver }}
          # Target platform for build
          # target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          modules: 'qtcharts qtscript qtwebengine'
          cached: 'false'

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # msvc编译
      - name: msvc-build
        id: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          qmake CaptureStream.pro
          make
 #         nmake
      - uses: actions/upload-artifact@v2
        with:
          name: CaptureStream
          path: ./
