name: C/C++ CI ubuntu

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        host: 'linux'
        target: 'desktop'
        version: '5.12'
        modules: 'qtcharts qtscript qtwebengine'

        
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile
    - name: make
      run: make
  
    - uses: actions/upload-artifact@v2
      with:
        name: CaptureStream
        path: ./
