name: C/C++ CI win

env:
  QT_VERSION:     "5.12.7"
  MINGW_VERSION:  "win32_mingw73"
  MINGW_PATH:     "mingw73_32"

on:
  workflow_dispatch:
     branches: [ master ]
      
jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
       include:
        - qt_ver: 5.9.9
          qt_arch: win32_msvc2015
          msvc_arch: x86
          qt_arch_install: msvc2015
        - qt_ver: 5.12.10
          qt_arch: win32_msvc2017
          msvc_arch: x86
          qt_arch_install: msvc2017
        - qt_ver: 5.15.2
          qt_arch: win32_msvc2019
          msvc_arch: x86
        - qt_ver: 5.9.9
          qt_arch: win32_mingw73
          msvc_arch: x86
          qt_arch_install: ingw73_32
          
          
    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        
    - uses: actions/checkout@v2.3.4

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.11.1
      with:
        version: ${{ matrix.qt_ver }}
        target: ${{ matrix.qt_target }}
        arch: ${{ matrix.qt_arch }}
        dir: ${{ github.workspace }}
        cached: 'false'

    - name: qmake
      run: qmake -makefile
    - name: make
      run: make
  
    - uses: actions/upload-artifact@v2
      with:
        name: CaptureStream
        path: ./
