name: Ubuntu
on:
  workflow_dispatch:
      branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.2.*
          cached: 'false'
          modules: 'qtcharts'
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev build-essential libgl1-mesa-dev
        
      - name: Install LinuxDeployQt
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage
        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          cmake ./ ./
          make
          linuxdeployqt-continuous-x86_64.AppImage CaptureStream
          
      - uses: actions/upload-artifact@v4
        with:
           name: CaptureStream
           path: ./
