name: Ubuntu
on:
  workflow_dispatch:
      branches: [ master ]
      paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/ubuntu.yml' 
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,ubuntu-20.04]
        qt_ver: [5.9.9,5.12.10,5.15.2]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
          version: 6.5.*
          modules: 'qtcharts'
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          qmake -makefile
          make
          
      - uses: actions/upload-artifact@v3
        with:
           name: CaptureStream
           path: ./
