name: Ubuntu
on:
  workflow_dispatch:
      branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.*
          cached: 'false'
          modules: 'qtcharts'
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev build-essential libgl1-mesa-dev
        
      - name: Install LinuxDeployQt
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage
        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          mkdir lib
          cp -r ../Qt/6.5.3/gcc_64/lib ./local/
          cp -r ../Qt/6.5.3/gcc_64/plugins ./local/
          cmake ./ ./ -CMAKE_INSTALL_RPATH="./local/lib"
          make
          mkdir Build
          cp -r  ./local ./Build/
          cp -r  CaptureStream ./Build/
          cp -r  ./qss_files/stylesheet-ubu.qss ./Build/

          
      - uses: actions/upload-artifact@v4
        with:
           name: CaptureStream
           path: ./Build
