name: Ubuntu
on:
  workflow_dispatch:
      branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.*
          cached: 'false'
          modules: 'qtcharts'
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          cmake ./ ./
          make
          
      - uses: actions/upload-artifact@v3
        with:
           name: CaptureStream
           path: ./
